//
// Generated by JTB 1.3.2
//

package lab2.syntaxtree;

/**
 * Grammar production:
 * f0 -> Expression()
 * f1 -> ( ExpressionRest() )*
 */
public class ExpressionList implements Node {
   public Expression f0;
   public NodeListOptional f1;

   public ExpressionList(Expression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(lab2.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(lab2.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(lab2.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(lab2.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

